FROM ikus060/docker-wine-maven:3-jdk-8

ARG MINARCA_VERSION

RUN curl -L https://www.ikus-soft.com/archive/minarca/minarca-client_${MINARCA_VERSION}.exe -o /tmp/minarca-install.exe && \
  export DISPLAY=:1 && \
  (Xvfb :1 -screen 0 1280x960x24 &) && \
  (wine /tmp/minarca-install.exe /S || true) && \
  echo '#!/bin/bash' > /usr/bin/minarca && \
  echo 'wine "C:\\users\\root\\Local Settings\\Application Data\\minarca\\bin\\minarca.exe" "$@"' >> /usr/bin/minarca && \  
  chmod +x /usr/bin/minarca && \
  minarca --version

ADD test.sh /
RUN chmod +x /test.sh

# Current version of openssh is not running fine in wine. So let only test if the installation is working.
#CMD [ "/test.sh" ]
CMD [ "/usr/bin/minarca", "--version" ]