ARG DIST=buster

FROM buildpack-deps:${DIST}

ARG MINARCA_VERSION


RUN curl -L https://www.ikus-soft.com/archive/minarca/get-minarca.sh -o /tmp/get-minarca.sh && \
  bash /tmp/get-minarca.sh --dev --package minarca-client --version "$MINARCA_VERSION" && \
  rm /tmp/get-minarca.sh && \
  /opt/minarca/bin/minarca --version
  
ADD test.sh /
RUN chmod +x /test.sh

CMD [ "/test.sh" ]