FROM buildpack-deps:buster

EXPOSE 22
EXPOSE 8080

ARG MINARCA_VERSION

RUN curl --fail -L https://www.ikus-soft.com/archive/minarca/get-minarca.sh -o /tmp/get-minarca.sh && \
  bash /tmp/get-minarca.sh --dev --version "$MINARCA_VERSION" && \
  rm /tmp/get-minarca.sh && \
  ssh-keygen -A && \
  mkdir -p /run/sshd && \
  sed -i 's/^LogFile/#LogFile/' /etc/minarca/minarca-server.conf && \
  sed -i 's/^LogAccessFile/#LogAccessFile/' /etc/minarca/minarca-server.conf

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:8080/ || exit 1
  
CMD [ "bash", "-c", "(/usr/sbin/sshd -D &) && /opt/minarca-server/bin/rdiffweb --config=/etc/minarca/minarca-server.conf" ]

