FROM buildpack-deps:buster

EXPOSE 22
EXPOSE 8080

ARG MINARCA_VERSION

RUN curl --fail -L https://www.ikus-soft.com/archive/minarca/get-minarca.sh -o /tmp/get-minarca.sh && \
  bash /tmp/get-minarca.sh --dev --version "$MINARCA_VERSION" && \
  rm /tmp/get-minarca.sh && \
  ssh-keygen -A && \
  mkdir -p /run/sshd && \
  touch /var/log/auth.log && \
  touch /var/log/minarca/shell.log && \
  touch /var/log/minarca/server.log && \
  touch /var/log/minarca/access.log && \
  chown minarca:minarca /var/log/minarca/*

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:8080/ || exit 1
  
CMD [ "bash", "-c", "(/usr/sbin/sshd -D &) && (/opt/minarca-server/bin/rdiffweb &) && tail -f /var/log/auth.log /var/log/minarca/*.log" ]

