ARG DIST=debian:buster
FROM ${DIST}

EXPOSE 22
EXPOSE 8080

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
      ca-certificates \
      curl

ARG MINARCA_SERVER_VERSION

RUN curl --fail -L https://www.ikus-soft.com/archive/minarca/get-minarca.sh -o /tmp/get-minarca.sh && \
  bash /tmp/get-minarca.sh --dev --package minarca-quota-api --version "$MINARCA_SERVER_VERSION"  && \
  rm /tmp/get-minarca.sh && \
  rm /etc/minarca/minarca-quota-api.conf

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:8081/ || exit 1
  
CMD [ "/opt/minarca-quota-api/bin/minarca-quota-api" ]
